---
repos:
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.6.0-1
    hooks:
      - id: shfmt
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.23
    hooks:
      - id: actionlint
  - repo: local
    hooks:
      - id: tflint
        name: TFLint
        description: Runs TFLint on all modules.
        files: '(\S+)\.tf$'
        language: script
        entry: ./scripts/tflint.sh
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
        args:
          - "--args=-diff"
          - "--args=-recursive"
      - id: terraform_docs
        args:
          - "--args=--hide=resources"
          - "--args=--hide-empty=true"
      - id: terraform_tfsec
