---
name: platform/management deploy

on:
  workflow_dispatch:
    inputs:
      destroy:
        type: boolean
        description: Destroy environment?
        required: true
        default: false

  push:
    paths:
      - platform/management/**

env:
  working_dir: platform/management
  key_vault: kv-schillman-management

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    environment: tfplan
    defaults:
      run:
        working-directory: ${{ env.working_dir }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Log in to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download -var-file for terraform plan/apply
        uses: azure/CLI@v1.0.9
        with:
          inlineScript: |
            az keyvault secret download --vault-name ${{ env.key_vault }} -n tf-secrets-base64 --f $GITHUB_WORKSPACE/tf-secrets.txt -e base64
            base64 -d $GITHUB_WORKSPACE/tf-secrets.txt > $GITHUB_WORKSPACE/tf-secrets.decoded.json

      - uses: Azure/get-keyvault-secrets@v1.1
        id: keyvault
        with:
          keyvault: ${{ env.key_vault }}
          secrets: "key, storage-account-name, container-name, resource-group-name"

      - name: Prep environment variables for terraform
        run: |
          {
            echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}"
            echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}"
          } >> $GITHUB_ENV

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: |
          terraform init -backend-config="resource_group_name=${{ steps.keyvault.outputs.resource-group-name }}" \
            -backend-config="storage_account_name=${{ steps.keyvault.outputs.storage-account-name }}" \
            -backend-config="container_name=${{ steps.keyvault.outputs.container-name }}" \
            -backend-config="key=${{ steps.keyvault.outputs.key }}"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Calculate destroy arg
        id: destroy_arg
        run: |
          if [ "${{ github.event.inputs.destroy }}" == "true" ]; then
            echo "val=-destroy" >> $GITHUB_OUTPUT
          else
            echo "val=" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -var-file=$GITHUB_WORKSPACE/tf-secrets.decoded.json \
            ${{ steps.destroy_arg.outputs.val }} -no-color -out=${{ github.workspace }}/out.tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Create the plan summary
        uses: actions/github-script@v6
        if: always()
        id: summary
        env:
          PLAN: "${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Prep the output
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }},
            --
            Action: \`${{ github.event_name }}\`,
            Working Directory: \`${{ env.working_dir }}\`,
            Workflow: \`${{ github.workflow }}\`*`;

            // 2. Set the output variable
            const fs = require('fs');
            fs.writeFileSync('${{ env.working_dir }}/summary.md', output);
            core.setOutput('summary', output);

      - name: Write the step summary
        if: always()
        run: cat summary.md >> $GITHUB_STEP_SUMMARY

      - name: Upload the plan
        uses: actions/upload-artifact@v3
        id: tfplanupload
        if: steps.plan.outcome != 'failure'
        with:
          name: ${{ format('{0}-tfplan', github.run_number) }}
          path: ${{ github.workspace }}/out.tfplan
          retention-days: 5

      - name: Publish plan as a status
        if: github.event_name == 'push'
        uses: Sibz/github-status-action@v1.1.6
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: ${{ steps.fmt.outcome }}
          context: Terraform Plan
          description: Terraform Plan Summary
          sha: ${{ github.event.push.head.sha }}

  apply:
    name: Terraform apply
    needs: [plan]
    runs-on: ubuntu-latest
    environment: tfapply
    defaults:
      run:
        working-directory: ${{ env.working_dir }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/download-artifact@v3

      - name: Log in to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: Azure/get-keyvault-secrets@v1.1
        with:
          keyvault: ${{ env.key_vault }}
          secrets: "key, storage-account-name, container-name, resource-group-name"
        id: keyvault

      - name: Terraform Init
        id: init
        run: |
          terraform init -backend-config="resource_group_name=${{ steps.keyvault.outputs.resource-group-name }}" \
            -backend-config="storage_account_name=${{ steps.keyvault.outputs.storage-account-name }}" \
            -backend-config="container_name=${{ steps.keyvault.outputs.container-name }}" \
            -backend-config="key=${{ steps.keyvault.outputs.key }}"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Download the plan
        uses: actions/download-artifact@v3
        with:
          name: ${{ format('{0}-tfplan', github.run_number) }}

      - name: Apply the plan
        id: apply
        run: |
          terraform apply -auto-approve \
            -no-color ${{ github.workspace }}/out.tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Create the plan summary
        uses: actions/github-script@v6
        if: always()
        id: summary
        env:
          APPLY: "${{ steps.apply.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Prep the output
            const output = `#### Terraform Apply 🚗\`${{ steps.apply.outcome }}\`

            <details><summary>Show details</summary>

            \`\`\`\n
            ${process.env.APPLY}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }},
            ---
            Action: \`${{ github.event_name }}\`,
            Working Directory: \`${{ env.working_dir }}\`,
            Workflow: \`${{ github.workflow }}\`*`;

            // 2. Set the output variable
            const fs = require('fs');
            fs.writeFileSync('${{ env.working_dir }}/summary.md', output);
            core.setOutput('summary', output);

      - name: Write the step summary
        if: always()
        run: cat summary.md >> $GITHUB_STEP_SUMMARY

      - name: Publish apply as a status
        if: github.event_name == 'push'
        uses: Sibz/github-status-action@v1.1.6
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: ${{ steps.summary.outputs.summary }}
          context: Terraform Plan
          description: Terraform Plan Summary
          sha: ${{ github.event.push.head.sha }}
